package httpserver

import (
	"bytes"
	"net/http"
	"path/filepath"
	"testing"
	"time"

	"github.com/nananek/miauth-private-portal/internal/domain"
	"github.com/nananek/miauth-private-portal/internal/health"
	"github.com/nananek/miauth-private-portal/internal/logging"
	"github.com/nananek/miauth-private-portal/internal/miauth"
	"github.com/nananek/miauth-private-portal/internal/openwebui"
	"github.com/nananek/miauth-private-portal/internal/storage/sqlite"
	"github.com/nananek/miauth-private-portal/internal/timeline"
)

// virtualActorTestServer bundles a real Server wired with a real
// internal/openwebui.Registry as its VirtualActors resolver, and one
// seeded VirtualActor. Building an actual Registry against the same
// database — rather than a hand-built fake VirtualActorResolver — is
// deliberate: the point of these tests is that resolveUserLite's
// projection and internal/openwebui's own eligibility rules (an active
// model, an enabled workspace) actually agree with each other end to
// end, which a fake resolver could silently paper over.
type virtualActorTestServer struct {
	*noteAPITestServer
	registry *openwebui.Registry
	virtual  domain.VirtualActor
}

// newVirtualActorTestServer builds a full note-API server exactly as
// newNoteAPITestServer does, plus a seeded Open WebUI registry wired as
// the server's VirtualActors resolver.
func newVirtualActorTestServer(t *testing.T) *virtualActorTestServer {
	t.Helper()
	path := filepath.Join(t.TempDir(), "test.db")
	db, err := sqlite.Open(t.Context(), sqlite.Config{Path: path, BusyTimeout: 5 * time.Second, MaxOpenConns: 4})
	if err != nil {
		t.Fatalf("open test database: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })
	if err := db.Migrate(t.Context()); err != nil {
		t.Fatalf("migrate test database: %v", err)
	}
	if err := db.Actors.EnsureReservedActors(t.Context()); err != nil {
		t.Fatalf("ensure reserved actors: %v", err)
	}

	miauthCfg := defaultMiAuthTestConfig()
	clock := &fakeTimelineClock{now: time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)}
	timelineSvc := timeline.NewService(db, db.Repos, timeline.Config{Clock: clock, OwnerUsername: miauthCfg.OwnerUsername})
	miauthSvc := miauth.NewService(db, db.Repos, miauthCfg)

	registry := openwebui.NewRegistry(db, db.Repos, openwebui.RegistryConfig{
		Enabled:          true,
		BaseURL:          "https://openwebui.example.net",
		SecretRef:        openwebui.SecretRefAPIKey,
		WorkspaceName:    "Open WebUI",
		PresentationHost: "openwebui.example.net",
		ModelDisplayName: "GPT-OSS 20B",
		ModelSlug:        "model",
		DefaultModelID:   "gpt-oss:20b",
	}, clock)
	if err := registry.Seed(t.Context()); err != nil {
		t.Fatalf("seed Open WebUI registry: %v", err)
	}
	virtual, err := registry.DefaultVirtualActor(t.Context())
	if err != nil {
		t.Fatalf("resolve default VirtualActor: %v", err)
	}

	logger := logging.New(&bytes.Buffer{}, logging.Config{Format: "json", Level: "info"})
	reg := health.NewRegistry()
	srv := NewServer(logger, reg, Options{
		MiAuthService:   miauthSvc,
		TimelineService: timelineSvc,
		LocalOrigin:     testLocalOrigin,
		VirtualActors:   registry,
	})

	ts := &noteAPITestServer{Server: srv, db: db, timeline: timelineSvc, clock: clock}
	ts.token, ts.ownerID = mustIssueToken(t, ts.Server, "virtualactor-setup", "read:account,write:notes")
	return &virtualActorTestServer{noteAPITestServer: ts, registry: registry, virtual: virtual}
}

// TestResolveUserLite_ProjectsVirtualActorAcrossEveryNoteRoute is Issue
// #52's contract test: an entry authored by a VirtualActor must resolve
// to the same non-null, presentation-host projection through every note
// route that returns a note.user (show, timeline, conversation,
// children), not just one of them.
func TestResolveUserLite_ProjectsVirtualActorAcrossEveryNoteRoute(t *testing.T) {
	ts := newVirtualActorTestServer(t)

	createRec := ts.post(t, "/api/notes/create", map[string]any{"text": "root post"})
	var created createdNoteResponse
	mustDecode(t, createRec, &created)
	rootID := created.CreatedNote.ID

	reply, err := ts.timeline.CreateGeneratedReplyBy(t.Context(), ts.virtual.ActorID, rootID, "generated by the model", nil)
	if err != nil {
		t.Fatalf("CreateGeneratedReplyBy: %v", err)
	}

	assertVirtualActorProjection := func(t *testing.T, got userLite) {
		t.Helper()
		if got.ID != ts.virtual.ActorID {
			t.Errorf("user.id = %q, want the VirtualActor's actor id %q", got.ID, ts.virtual.ActorID)
		}
		if got.Username != ts.virtual.Slug {
			t.Errorf("user.username = %q, want the model slug %q", got.Username, ts.virtual.Slug)
		}
		if got.Host == nil || *got.Host != ts.virtual.Host {
			t.Errorf("user.host = %v, want the presentation host %q", got.Host, ts.virtual.Host)
		}
	}

	t.Run("show", func(t *testing.T) {
		rec := ts.post(t, "/api/notes/show", map[string]any{"noteId": reply.ID})
		if rec.Code != http.StatusOK {
			t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
		}
		var n note
		mustDecode(t, rec, &n)
		if n.UserID != ts.virtual.ActorID {
			t.Errorf("userId = %q, want %q", n.UserID, ts.virtual.ActorID)
		}
		assertVirtualActorProjection(t, n.User)
	})

	t.Run("timeline", func(t *testing.T) {
		rec := ts.post(t, "/api/notes/timeline", map[string]any{"limit": 10})
		if rec.Code != http.StatusOK {
			t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
		}
		var notes []note
		mustDecode(t, rec, &notes)
		found := false
		for _, n := range notes {
			if n.ID == reply.ID {
				found = true
				assertVirtualActorProjection(t, n.User)
			}
		}
		if !found {
			t.Fatalf("timeline did not include the VirtualActor's reply %q: %+v", reply.ID, notes)
		}
	})

	t.Run("conversation", func(t *testing.T) {
		// /api/notes/conversation returns a note's *ancestor* chain, not
		// the note itself (see TestHandleNotesConversation_
		// OldestFirstAncestorsExcludingHidden), so the VirtualActor's
		// reply is put where it can actually appear: as an ancestor of a
		// further owner reply.
		grandchildRec := ts.post(t, "/api/notes/create", map[string]any{"text": "owner follow-up", "replyId": reply.ID})
		var grandchild createdNoteResponse
		mustDecode(t, grandchildRec, &grandchild)

		rec := ts.post(t, "/api/notes/conversation", map[string]any{"noteId": grandchild.CreatedNote.ID})
		if rec.Code != http.StatusOK {
			t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
		}
		var notes []note
		mustDecode(t, rec, &notes)
		found := false
		for _, n := range notes {
			if n.ID == reply.ID {
				found = true
				assertVirtualActorProjection(t, n.User)
			}
		}
		if !found {
			t.Fatalf("conversation did not include the VirtualActor's reply %q: %+v", reply.ID, notes)
		}
	})

	t.Run("children", func(t *testing.T) {
		rec := ts.post(t, "/api/notes/children", map[string]any{"noteId": rootID})
		if rec.Code != http.StatusOK {
			t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
		}
		var notes []note
		mustDecode(t, rec, &notes)
		if len(notes) != 1 || notes[0].ID != reply.ID {
			t.Fatalf("children = %+v, want exactly the VirtualActor's reply %q", notes, reply.ID)
		}
		assertVirtualActorProjection(t, notes[0].User)
	})
}

// TestResolveUserLite_VirtualActorFallsBackWhenNotResolvable checks the
// failure side of the same projection: once the model or its workspace
// stops being eligible (Issue #52's same two ResolveVirtualActor gates),
// an already-authored entry's author falls back to the ordinary
// actor-ID-as-username projection with a null host, exactly like any
// other unresolvable author — never a stale or partially-filled remote
// projection.
func TestResolveUserLite_VirtualActorFallsBackWhenNotResolvable(t *testing.T) {
	ts := newVirtualActorTestServer(t)
	createRec := ts.post(t, "/api/notes/create", map[string]any{"text": "root post"})
	var created createdNoteResponse
	mustDecode(t, createRec, &created)

	reply, err := ts.timeline.CreateGeneratedReplyBy(t.Context(), ts.virtual.ActorID, created.CreatedNote.ID, "body", nil)
	if err != nil {
		t.Fatalf("CreateGeneratedReplyBy: %v", err)
	}

	if err := ts.db.OpenWebUIWorkspaces.SetEnabled(t.Context(), ts.virtual.WorkspaceID, false, ts.clock.Now()); err != nil {
		t.Fatal(err)
	}

	rec := ts.post(t, "/api/notes/show", map[string]any{"noteId": reply.ID})
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
	}
	var n note
	mustDecode(t, rec, &n)
	if n.User.Host != nil {
		t.Errorf("user.host = %v, want nil once the workspace is disabled", n.User.Host)
	}
	if n.User.Username != ts.virtual.ActorID {
		t.Errorf("user.username = %q, want the actor-id fallback %q", n.User.Username, ts.virtual.ActorID)
	}
}

// TestResolveUserLite_FlagOffMatchesPreExistingFixtureExactly is the
// regression half of the plan: with the feature flag off (VirtualActors
// nil, the zero value every pre-Issue-#52 Server already had), an
// ordinary assistant-authored reply's projection is byte-for-byte what
// it was before this feature existed. This never touches an
// openwebui_model actor at all — there is no config path to create one
// with the flag off — so it is really re-confirming
// TestHandleNotesShow's existing assistant-actor behavior is unchanged
// by this PR's httpserver edits.
func TestResolveUserLite_FlagOffMatchesPreExistingFixtureExactly(t *testing.T) {
	ts := newNoteAPITestServer(t) // no VirtualActors wired
	createRec := ts.post(t, "/api/notes/create", map[string]any{"text": "root"})
	var created createdNoteResponse
	mustDecode(t, createRec, &created)

	gen := domain.LLMGeneration{
		ID: domain.NewID(), TargetEntryID: created.CreatedNote.ID, Kind: domain.GenerationReply,
		Provider: "test", Model: "test", PromptVersion: "v1", Status: domain.GenerationPending,
		RequestedAt: ts.clock.Now(),
	}
	if err := ts.db.Generations.Create(t.Context(), gen); err != nil {
		t.Fatal(err)
	}
	reply, err := ts.timeline.CreateGeneratedReply(t.Context(), created.CreatedNote.ID, domain.EntryLLMReply, "reply", gen.ID, nil, nil)
	if err != nil {
		t.Fatal(err)
	}

	rec := ts.post(t, "/api/notes/show", map[string]any{"noteId": reply.ID})
	if rec.Code != http.StatusOK {
		t.Fatalf("status = %d %q, want %d", rec.Code, rec.Body.String(), http.StatusOK)
	}
	var n note
	mustDecode(t, rec, &n)
	if n.User.Username != "assistant" {
		t.Errorf("user.username = %q, want %q", n.User.Username, "assistant")
	}
	if n.User.Host != nil {
		t.Errorf("user.host = %v, want nil", n.User.Host)
	}
}
